name: Action Test

on: [workflow_dispatch]
#  pull_request:
#    branches: [ master ]
  

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: 1
        run: |
          echo "1"
        shell: bash

  deploy-dev:
    name: Deploy Dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: 2
        run: |
          echo "2"
        shell: bash

  deploy-qa:
    name: Deploy QA
    needs: [deploy-dev]
    environment: 
      name: QA
    runs-on: ubuntu-latest
    steps:
      - name: 3
        run: |
          echo "3"
        shell: bash
